# Generated by Django 4.1.3 on 2022-11-12 23:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Medico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=15)),
                ('apellido_paterno', models.CharField(max_length=15)),
                ('apellido_materno', models.CharField(max_length=15)),
                ('edad', models.IntegerField()),
                ('fecha_nacimiento', models.DateField()),
                ('especialidad', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Prevision_Salud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=15)),
                ('apellido_paterno', models.CharField(max_length=15)),
                ('apellido_materno', models.CharField(max_length=15)),
                ('edad', models.IntegerField()),
                ('fecha_nacimiento', models.DateField()),
                ('prevision_salud', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.prevision_salud')),
            ],
        ),
    ]
