# Generated by Django 4.1.3 on 2022-11-13 00:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_paciente_edad'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medico',
            name='edad',
        ),
    ]
